version: 0.2
env:
  variables:
    S3_BUCKET: i-perf-test
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Start...
      - ls -lah
      - chmod +x launch.sh
      - yum update
      - yum install -y wget unzip
      # - chmod +x docker_distributed_jmeter.sh
      # - chmod +x ./scripts/test_execution.sh
  build:
    commands:
      - mkdir -p upload/html
      - mkdir -p upload/results
      - wget -q https://downloads.apache.org.//jmeter/binaries/apache-jmeter-5.4.3.zip
      - unzip -qq apache-jmeter-5.4.3.zip
      - cd apache-jmeter-5.4.3/bin
      - ls -lah
      - bash jmeter.sh -n -t ../../Test1.jmx -l ../../upload/results/results.csv -e -o ../../upload/html
      - cd ../../upload/results
      - ls -lah
      - cat results.csv
      - cd ../../
      - ls -lah
      - mv -i upload/results upload/html/results
      - cd upload/html
      - ls -lah
      # - cd ../../
      # - python3 scripts/s3_upload.py
      - aws s3 sync . s3://${S3_BUCKET} 
      # - docker build -t jmeter .
      # - docker-compose up -d
      # - bash ./scripts/test_execution.sh
      - echo "build completed"
