version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Start...
      - ls -lah
      - chmod +x launch.sh
      - chmod +x docker_distributed_jmeter.sh
      # - chmod +x ./scripts/test_execution.sh
  build:
    commands:
      - bash launch.sh
      - bash docker_distributed_jmeter.sh
       # - bash ./scripts/test_execution.sh
      - echo "build completed"
