version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Start...
      - ls -lah
      # - chmod +x jmeters
      - chmod +x ./docker_distributed_jmeter.sh
  build:
    commands:
      - bash ./docker_distributed_jmeter.sh
      - echo "build completed"
