version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Start...
      - ls -lah
      - chmod +x launch.sh
      - apt-get update
      - apt-get install -y wget unzip
      # - chmod +x docker_distributed_jmeter.sh
      # - chmod +x ./scripts/test_execution.sh
  build:
    commands:
      - mkdir -p html
      - mkdir -p report
      - wget https://downloads.apache.org.//jmeter/binaries/apache-jmeter-5.4.3.zip
      - unzip -qq apache-jmeter-5.4.3.zip
      - cd apache-jmeter-5.4.3/bin
      - ls -lah
      - bash jmeter.sh -n -t ../../test.jmx -l ../../report/results.csv -e -o ../../html
      - cd ../../report
      - ls -lah
      - cat results.csv
      - cd ../../html
      - ls -lah
      # - docker build -t jmeter .
      # - docker-compose up -d
      # - bash ./scripts/test_execution.sh
      - echo "build completed"
