#!/bin/sh

sudo mkdir -p html/1
sudo mkdir -p result/1

wget https://ftp.cixug.es/apache//jmeter/binaries/apache-jmeter-5.4.1.tgz -o apache-jmeter-5.4.1.tgz;
tar -xvzf apache-jmeter-5.4.1.tgz;
cd apache-jmeter-5.4.1/bin
 